[theme]
primaryColor = "#6C63FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F0FF"
textColor = "#1F2937"
font = "Open Sans"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = true
