[theme]
primaryColor = "#6C63FF"
backgroundColor = "#0B071D"
secondaryBackgroundColor = "#151136"
textColor = "#E8EBFF"
font = "Open Sans"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = true
